name: Build sdist

on:
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_artifacts:
    name: Build sdist
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install PyBuild
        run: |
          python -m pip install -U build
      - name: Build sdist
        run: |
          python -m build --sdist .
      - uses: actions/upload-artifact@v5
        with:
          name: sdist
          path: dist

  test_artifacts:
    name: Test sdist
    needs: [build_artifacts]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: sdist
          path: dist
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - run: |
          ls
          ls dist
          python -m pip install -U twine setuptools build wheel numpy "cython>=3.1.4"
          python -m twine check dist/*
          python -m pip install --upgrade --no-build-isolation --no-cache-dir --no-deps --pre --no-index --find-links=dist phasorpy
          python -c"from phasorpy import __version__;print(__version__)"

# Upload sdist and wheels manually for now
#
#  upload_artifacts:
#    name: Upload release to PyPI
#    needs: [test_artifacts]
#    runs-on: ubuntu-latest
#    environment:
#      name: pypi
#      url: https://pypi.org/p/phasorpy
#    permissions:
#      id-token: write
#    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
#    steps:
#      - uses: actions/download-artifact@v6
#        with:
#          name: releases
#          path: dist
#      - uses: pypa/gh-action-pypi-publish@release/v1
