name: Publish to PyPI

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build_artifacts:
    name: Build sdist and wheel
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install PyBuild
        run: |
          python -m pip install build
      - name: Build wheel and sdist
        run: |
          python -m build .
      - uses: actions/upload-artifact@v3
        with:
          name: releases
          path: dist

  test_artifacts:
    name: Test sdist and wheel
    needs: [build_artifacts]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: releases
          path: dist
      - uses: actions/setup-python@v4.6.0
        with:
          python-version: "3.11"
      - run: |
          ls
          ls dist
          python -m pip install -U twine
          python -m twine check dist/*
          python -m pip install --upgrade --no-cache-dir --no-deps --pre --no-index --find-links=dist phasorpy
          python -c"from phasorpy import __version__;print(__version__)"

  upload_artifacts:
    name: Upload release to PyPI
    needs: [build_artifacts]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/phasorpy
    permissions:
      id-token: write
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: releases
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
